# Generated by Django 2.1.7 on 2019-02-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('pub_status', models.CharField(max_length=100)),
                ('latest_chapter', models.IntegerField(default=0)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('release_date', models.DateField()),
                ('url_chapter', models.CharField(max_length=200)),
                ('url_metadata', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mangagenre',
            unique_together={('manga', 'genre')},
        ),
    ]
